### ISSUE TITLE
Custom attribute on the service contract does not work.

### ISSUE THREAD

**Issue by catwarrior** [jweber/WcfClientProxyGenerator#21]
Hi jweber,

Greate library!

but I found it seems the custom attribute on the service contract won't work after using the library, because the interface generated won't inherit the attributes on the original interface.  

Thanks,

**Comment by catwarrior** [comment]
After reviewing the implementation, I saw 

in `DynamicProxyTypeGenerator`.`GenerateTypes`, you clone the `ServiceContractAttribute` to the generated interface.

I think probably you could just clone all the attribute that the original interface have.

What do you thinks?

Thanks,

**Comment by jweber** [comment]
I was actually thinking about that the other day so thanks for letting me know it's an issue that you're having. Version 2.2.4 was just pushed up to NuGet which added copying of custom attributes to both the generated service interface and generated methods on that interface. Let me know how that works for you!

**Comment by catwarrior** [comment]
Great! thanks.
