### ISSUE TITLE
Version 2.2.4 caused System.InvalidOperationException

### ISSUE THREAD

**Issue by HassanGulzar** [jweber/WcfClientProxyGenerator#22]
Here is the exception:

The synchronous OperationContract method 'GetCompaniesForLookup' in type 'DA.Services.CarPark.ServiceContracts.Common.v1.ILookupService' was matched with the task-based asynchronous OperationContract method 'GetCompaniesForLookupAsync' because they have the same operation name 'GetCompaniesForLookup'. When a synchronous OperationContract method is matched to a task-based asynchronous OperationContract method, any additional attributes must be declared on the synchronous OperationContract method. In this case, the task-based asynchronous OperationContract method 'GetCompaniesForLookupAsync' has one or more attributes of type 'FaultContractAttribute'. To fix it, remove the 'FaultContractAttribute' attribute or attributes from method 'GetCompaniesForLookupAsync'. Alternatively, changing the name of one of the methods will prevent matching.

Stack:
```
System.ServiceModel.Description.TypeLoader.SyncTaskOperationConsistencyVerifier.VerifyFaultContractAttribute()
System.ServiceModel.Description.TypeLoader.VerifyConsistency(OperationConsistencyVerifier verifier)
System.ServiceModel.Description.TypeLoader.CreateOperationDescription(ContractDescription contractDescription, MethodInfo methodInfo, MessageDirection direction, ContractReflectionInfo reflectionInfo, ContractDescription declaringContract)
System.ServiceModel.Description.TypeLoader.CreateOperationDescriptions(ContractDescription contractDescription, ContractReflectionInfo reflectionInfo, Type contractToGetMethodsFrom, ContractDescription declaringContract, MessageDirection direction)
System.ServiceModel.Description.TypeLoader.CreateContractDescription(ServiceContractAttribute contractAttr, Type contractType, Type serviceType, ContractReflectionInfo& reflectionInfo, Object serviceImplementation)
System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
System.ServiceModel.Description.ContractDescription.GetContract(Type contractType)
WcfClientProxyGenerator.ChannelFactoryProvider.GetClientEndpointConfiguration[TServiceInterface](Type serviceInterfaceType, String endpointConfigurationName)
WcfClientProxyGenerator.ChannelFactoryProvider.<>c__DisplayClass2_0`1.<GetChannelFactory>b__0()
WcfClientProxyGenerator.ChannelFactoryProvider.<>c__DisplayClass9_0`1.<GetChannelFactory>b__0(String _)
WcfClientProxyGenerator.Util.DictionaryExtensions.<>c__DisplayClass0_0`2.<GetOrAddSafe>b__0()
System.Lazy`1.CreateValue()
```

My sample solution at https://github.com/jweber/WcfClientProxyGenerator/issues/19#issuecomment-217573211 would exhibit this behavior. For now, I'm reverting to 2.2.3. 

Thanks!

**Comment by jweber** [comment]
Ah, thanks. I'll de-list 2.2.4 from NuGet until this can be looked at.

**Comment by jweber** [comment]
This issue was taken care of so you should be good to upgrade to 2.2.5 if desired. Thanks for quickly reporting this!

**Comment by dandrejvv** [comment]
Hi. I'm using version 2.2.5 and I'm getting this exception on an interface that only has non-async operations on it. I've tried to revert to 2.2.3 but still no luck. I'm not sure if I can post the contract as is but I'll try to rename everything as much as I can without giving away exactly what it is or what it is used for in my current line of business work.

```c#

    [ServiceContract(
        Namespace = Constants.NAMESPACE,
        Name = "SomeVendorServices")]
    public interface ISomeVendorServices
    {
        [OperationContract]
        Operation1Response GetOperation1(Operation1Request request);

        [OperationContract]
        Operation2Response RequestOperation2(Operation2Request request);

        [OperationContract]
        Operation3Response RequestOperation3(Operation3Request request);

        [OperationContract]
        Operation4Response RequestOperation4(Operation4Request request);

        [OperationContract]
        Operation5Response GetOperation5(Operation5Request request);
    }

    static class Constants
    {
        public const string NAMESPACE = "SomeDomain.Contracts";
    }
```
