### ISSUE TITLE
Version 2.2.5 caused System.InvalidOperationException

### ISSUE THREAD

**Issue by dandrejvv** [jweber/WcfClientProxyGenerator#25]
Hi. I'm using version 2.2.5 and I'm getting the same exception (as #22) on an interface that only has non-async operations on it. I've tried to revert to 2.2.3 but still no luck. I'm not sure if I can post the contract as is but I'll try to rename everything as much as I can without giving away exactly what it is or what it is used for in my current line of business work.

``` c#

    [ServiceContract(
        Namespace = Constants.NAMESPACE,
        Name = "SomeVendorServices")]
    public interface ISomeVendorServices
    {
        [OperationContract]
        Operation1Response GetOperation1(Operation1Request request);

        [OperationContract]
        Operation2Response RequestOperation2(Operation2Request request);

        [OperationContract]
        Operation3Response RequestOperation3(Operation3Request request);

        [OperationContract]
        Operation4Response RequestOperation4(Operation4Request request);

        [OperationContract]
        Operation5Response GetOperation5(Operation5Request request);
    }

    static class Constants
    {
        public const string NAMESPACE = "SomeDomain.Contracts";
    }

    WcfClientProxy.Create<ISomeVendorServices>(d => d.UseDefaultEndpoint())
```

I've created this even in a clean console app and it still failed.

I'm using Visual Studio 2015 with .NET 4.5.2

**Comment by ElijahReva** [comment]
Same for me!

**Comment by jweber** [comment]
It's been a while since I've had a chance to do any work with this library, but this issue is now resolved by the changes in the associated commits. Versions [2.2.6](https://www.nuget.org/packages/WcfClientProxyGenerator/2.2.6) and [2.3.0-alpha4](https://www.nuget.org/packages/WcfClientProxyGenerator/2.3.0-alpha4) on NuGet have the fix.
