### ISSUE TITLE
.Net Framework 4.8

### ISSUE THREAD

**Issue by DoomerDGR8** [jweber/WcfClientProxyGenerator#29]
For reasons I cannot explain (2 days of continuous debugging), when I upgraded two of my running project to .Net 4.8, I started to get he message with Action 'http://carpark.company.com/services/internal/ILookupService/GetRequestTypes' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver. Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

Reverting back to 4.7.2 resolves this.

Could you find time to validate this?

**Comment by jweber** [comment]
I may get a chance over the next few days to look more into this, but I couldn't recreate your issue on my first attempt. Which version are you using? You can try giving the [2.3.0-alpha4](https://www.nuget.org/packages/WcfClientProxyGenerator/2.3.0-alpha4) release a chance and see if that fixes things. It's been seeing significant production use but I just haven't had the opportunity to fully release it.

**Comment by DoomerDGR8** [comment]
Sorry, yes I'm on the latest alpha. And I'm still trying to figure this one out.

**Comment by DoomerDGR8** [comment]
I have come to the conclusion that this issue is isolated to me and over a few projects only. I have rebuilt a project from scratch and got it working fine. I'm closing this issue now.
